name: CI

on: 
  push:
    branches:
      - main
# on es el gatillador en ese pipeline, ¿qué acción va a ser el usuario para que
# ese trigger se ejecute? se define tambien en que rama del repositorio se ejecuta
# el pipeline. En este caso decimos que el pipeline se va a ejecutar/gatillar cuando
# el usuario haga push en el repositorio pero en las ramas: 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # ese primer paso es obligatorio porque este checkout lo que hace por defecto
      # es clonar el proyecto que está en nuestro repositorio a la máquina virtual
      # que esta habilitando github.

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        
      # aca se instala uv
      # ejecuta todos los comandos necesarios para instalar uv

      - name: Instalar dependencias
        run: |
          uv sync
      # instala todas las dependencias incluyendo ruff, pytest, mypy
      # crea tambien el environment
      # con 'run' ejecutas comandos
      
      - name: Ruff lint
        run: |
          uv run ruff check .

      - name: Ruff format
        run: |
          uv run ruff format --check .

      - name: Mypy
        run: |
          uv run mypy my_app

      - name: Run Tests
        run: |
          uv run pytest

      # correr los test con pytest
      

  # es un job, dentro de cada job tiene subtareas, si fuera un pipeline de vertex
  # ese pipeline tiene tareas o componentes, el job es el general
  # dentro de este job llamado 'test' vamos a tener varios pasos/steps o componentes
  # se puede tener varios jobs pero cada job tendrá pasos a seguir
  # ubuntu-latest define bajo que sistema operativo se ejecuta el código,
  # no es que se ejecuta en github, sino que ella habilita una maquina virtual por atras
  # y aquí se define el sistema operativo de esa máquina
  # Cada steps tiene un nombre y luego tiene lo que va a ejecutar, puede ser código
  # o acción pre-construida, básicamente es como si estuvieras importando una librería